### PR TITLE
Expose CI=true and GITHUB_ACTIONS env variables

### LINKED ISSUE #211: kubernetes mode missing required environment variables
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.11.0

### Deployment Method

ArgoCD

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Create a regular autoscalingrunnerset
2. Create an autoscalingrunnerset with container mode "kubernetes"
3. Run a workflow that displays the environment variables (like `env`)
4. In kubernetes mode, variables like `GITHUB_ACTIONS` and `CI` are missing
```

### Describe the bug

In kubernetes mode, variables like `GITHUB_ACTIONS` and `CI` are missing, even though these are specified as being [default environment variables])https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables).

### Describe the expected behavior

Both `GITHUB_ACTIONS` and `CI` environment variables should be present and contain the value `true`

### Additional Context

```yaml
Runner setup snippets from helm values


containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    storageClassName: default
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi

template:
  spec:
    securityContext:
      fsGroup: 123
    containers:
      - command:
          - /home/runner/run.sh
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
            value: /home/runner/k8s/index.js
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: 'true'
        image: 'ghcr.io/actions/actions-runner:latest'
        name: runner
        volumeMounts:
          - mountPath: /home/runner/_work
            name: work
```

### Controller Logs

```shell
There doesn't seem to be an error with the controller, but for completeness, here it is https://gist.github.com/reiniertimmer/547744ef5178b90b27f09b04ade3f576
```

### Runner Pod Logs

```shell
https://gist.github.com/reiniertimmer/ca2cdaca95706c1bc945a100d30820bd
```

### PR DESCRIPTION
**Pull request by nikola-jokic**
Fixes #211

### CODE REVIEW

File: packages/k8s/src/hooks/prepare-job.ts [hunk 1]
```diff
@@ -229,6 +229,18 @@ export function createContainerSpec(
     }
   }
 
+  podContainer.env.push({
```
Comment (xoanmi) [inline packages/k8s/src/hooks/prepare-job.ts:232]: What if `podContainer.env['GITHUB_ACTIONS']` already exists? Should we manage it as we do with `CI` to prevent duplication?

File: packages/docker/src/dockerCommands/container.ts [hunk 2]
```diff
@@ -403,11 +408,16 @@ export async function containerRun(
   }
   if (args.environmentVariables) {
     for (const [key] of Object.entries(args.environmentVariables)) {
-      dockerArgs.push('-e')
-      dockerArgs.push(key)
+      dockerArgs.push('-e', key)
     }
   }
 
+  dockerArgs.push('-e', 'GITHUB_ACTIONS=true')
```
Comment (xoanmi) [inline packages/docker/src/dockerCommands/container.ts:415]: What if `podContainer.env['GITHUB_ACTIONS']` already exists? Should we manage it as with `CI` to prevent duplication?

File: packages/k8s/tests/prepare-job-test.ts [hunk 3]
```diff
@@ -62,6 +62,28 @@ describe('Prepare job', () => {
     ).resolves.not.toThrow()
   })
 
+  it('should prepare job with envs CI and GITHUB_ACTIONS', async () => {
```
Comment (xoanmi) [inline packages/k8s/tests/prepare-job-test.ts:65]: Should we include a test to confirm the outcome if either the `GITHUB_ACTIONS` or the `CI` environment variable already exists in the job definition?

**Review by xoanmi — APPROVED** [review]

**Review by Link- — APPROVED** [review]
